services:
  postgres:
    image: postgres:alpine
    networks:
      - app_net

  redis:
    image: redis:alpine
    networks:
      - app_net

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    environment:
      SMTP_USER:
      SMTP_SERVER:
      SMTP_PASSWORD:
    command: 'pipenv run worker'
    networks:
      - app_net

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      DEBUG: 1
      PREFERRED_URL_SCHEME: 'https'
      SERVER_NAME: 'ub-blade-01.bib.uni-mannheim.de'
    command: 'pipenv run webapp'
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
